In [1]:
import torch
import torch.functional as F

In [6]:
import numpy as np

In [7]:
np.set_printoptions(precision=3)

In [16]:
torch.softmax(torch.FloatTensor([1000,1006]),dim=0).numpy()

array([0.002, 0.998], dtype=float32)

In [21]:
torch.softmax(torch.FloatTensor([1, 1000]),dim=0).numpy()

array([0., 1.], dtype=float32)

In [28]:
torch.FloatTensor([10000000000000])

tensor([1.0000e+13])

In [30]:
from numpy.random import binomial

In [93]:
t = 0
for _ in range(1000):
    t += binomial(1,0.05)

In [95]:
from numpy.random import multinomial

In [210]:
t = multinomial(1,[0.33,0.33,0.33])
print(t)
np.argmax(t)

[1 0 0]


0

In [211]:
from scipy.stats import entropy

In [218]:
entropy([0.11824746, 0.11219074])

0.6928017298703899

In [219]:
5e5

500000.0