In [9]:
import numpy as np

In [63]:
class ReplayBuffer(object):
    def __init__(self, state_dim, action_dim, buffer_size): # Image state will be handled at ImageBuffer
        self.state_dim = state_dim
        self.action_dim = action_dim
        
        self.buffer_size = buffer_size
        self.count = 0
        self.ptr = 0
        
        self.s_buffer = np.zeros([buffer_size, state_dim])
        self.a_buffer = np.zeros([buffer_size, action_dim])
        self.r_buffer = np.zeros([buffer_size, 1])
        self.t_buffer = np.zeros([buffer_size, 1])
        self.s2_buffer = np.zeros([buffer_size, state_dim])
        
    
    def size(self):
        return self.count
    
    def add(self, s, a, r, t, s2):
        assert s.shape == (self.state_dim,)
        assert a.shape == (self.action_dim,)
        assert r.shape == (1,)
        assert t.shape == (1,)
        assert s2.shape == (self.state_dim,)
        
        self.s_buffer[self.ptr] = s
        self.a_buffer[self.ptr] = a
        self.r_buffer[self.ptr] = r
        self.t_buffer[self.ptr] = t
        self.s2_buffer[self.ptr] = s2
        
        self.count = min(self.count + 1, self.buffer_size)
        self.ptr = (self.ptr + 1) % self.buffer_size
        
    def sample_batch(self, batch_size):
        batch_size = min(self.count, batch_size)
        
        sample_idx = np.random.choice(self.count, batch_size, replace=False)
        
        return self.s_buffer[sample_idx], self.a_buffer[sample_idx], self.r_buffer[sample_idx], self.t_buffer[sample_idx], self.s2_buffer[sample_idx]
                
        

In [64]:
rb = ReplayBuffer(3, 2, 5)

In [65]:
rb.add(np.array([1,2,3]),np.array([-1,-2]),np.array([1.0]),np.array([True]),
       np.array([10,20,30]))

In [61]:
rb.add(np.array([[2,3,4]]),np.array([[-2,-3]]),np.array([[2.0]]),np.array([[True]]),
       np.array([[20,30,40]]))

In [66]:
rb.sample_batch(3)

(array([[1., 2., 3.]]),
 array([[-1., -2.]]),
 array([[1.]]),
 array([[1.]]),
 array([[10., 20., 30.]]))

In [69]:
np.array([1])

array([1])

In [77]:
x = int(input())

def zarisu(x):
    count = 0
    while x >= 1:
        count += 1
        x = int(x / 10)
    return count

zari = zarisu(x)

nums = 0
for idx in range(1, zari):
    nums += idx * (9 * 10**(idx-1))

nums += ((x - 10 ** (zari-1) ) + 1) * zari

print(nums)

120
252
